### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-public-api#25]
Using the Swagger API, I attempted to search for sample IDs with the defaults provided and received the following traceback

```
127.0.0.1 - - [28/Jun/2020 14:46:00] "GET /api/metadata/sample_ids?age_cat=30s&bmi_cat=Normal&taxonomy=genus-level-taxonomy&alpha_metric=faith_pd HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/connexion/decorators/response.py", line 103, in wrapper
    response = function(request)
  File "/Users/dtmcdonald/miniconda3/envs/microsetta-public-api/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/Users/dtmcdonald/ResearchWork/software/microsetta-public-api/microsetta_public_api/api/metadata.py", line 35, in filter_sample_ids
    return jsonify(*error_response), error_code
TypeError: jsonify() argument after * must be an iterable, not Response
```

**Comment by gwarmstrong** [comment]
Hmmmm... I think this is two separate issues. One with your config/request, and one with how I handled errors...

Can you post your config?

**Comment by gwarmstrong** [comment]
Here's what mine looks like:
```
{
  "alpha_resources": {
    "faith-pd": "/Users/garmstro/microsetta_public/alpha/faith_pd.qza",
    "shannon": "/Users/garmstro/microsetta_public/alpha/shannon.qza"
  },
  "table_resources": {
    "ag-raw": {
      "table": "/Users/garmstro/microsetta_public/taxa/ag.biom.nobloom.min2.min1k.qza",
      "feature-data-taxonomy": "/Users/garmstro/microsetta_public/taxa/ag.fna.nobloom.min2.min1k.taxonomy.qza"
    }
  },
  "metadata": "/Users/garmstro/microsetta_public/ag.txt"
}
```

**Comment by gwarmstrong** [comment]
Actually, the more likely alternative, if you are using a collapsed taxonomy the more likely answer is that your `FeatureData[Taxonomy]` and `FeatureTable` do not have aligned axes... Thought to support this use-case, but figured there were workarounds for now.

You can use the following python script (this is what I did locally), with your collapsed table as the `input_table`.
```
import pandas as pd
from qiime2 import Artifact
from biom import Table

input_table = '/Users/garmstro/microsetta_public/taxa/genus.qza'

output_taxonomy = '/Users/garmstro/microsetta_public/taxa/genus-taxonomy.qza'

feature_table = Artifact.load(input_table)
feature_table_biom = feature_table.view(Table)
taxa = feature_table_biom.ids('observation')
taxonomy = pd.DataFrame({'Taxon': taxa, 
			},
		        index=pd.Series(taxa, name='Feature ID'))
feature_data = Artifact.import_data("FeatureData[Taxonomy]", taxonomy)
feature_data.save(output_taxonomy)
```

**Comment by wasade** [comment]
It's qualitatively the same as your config. I think what's happening is an edge case on filtering samples:

```bash
  File "/Users/dtmcdonald/ResearchWork/software/microsetta-public-api/microsetta_public_api/api/metadata.py", line 35, in filter_sample_ids
    return jsonify(*error_response), error_code
TypeError: jsonify() argument after * must be an iterable, not Response
```

The query was requesting something that doesn't exist in the config, but that shouldn't trigger a 500 error

**Comment by gwarmstrong** [comment]
Agree that the 500 should not happen, will fix and add regression tests. For the the time being, creating a new `FeatureData[Taxonomy]` from the Feature Table (as shown in python script above) should _hopefully_ resolve your issue.
